version: "3.9"

services:
  strongly-typed-thoughts.net-webserver:
    image: strongly-typed-thoughts.net-webserver:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /opt/strongly-typed-thoughts.net/uploads:/opt/strongly-typed-thoughts.net/uploads
      - /opt/strongly-typed-thoughts.net/blog:/opt/strongly-typed-thoughts.net/blog

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
